name: Build and deploy main branch

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/ci-cd

jobs:
  build-and-deploy:
    concurrency:
      group: "build-${{github.ref}}"
      cancel-in-progress: false
    runs-on: "ubuntu-latest"
    environment: main
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 20.x Environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: "Pre build"
        run: "npm ci"
      - name: "Build"
        env:
          DOT_ENV_FILE: ".env.${{ github.ref_name }}"
        run: |
          if [ -f $DOT_ENV_FILE ]; then
            export $(grep -v '^#' $DOT_ENV_FILE | xargs -d '\n')
          fi
          npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID}}:role/${{vars.AWS_ROLE_NAME}}
          aws-region: "us-east-1"
      - name: "Deploy to s3"
        run: |
          aws s3 sync --no-progress ./dist/ s3://${{vars.S3_BUCKET}}/
